[package]
name = "quic-test"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quiche = "0"
log = "0"
env_logger = "0"
mio = "0"
ring = "0"
