[package]
name = "scraper-web-to-markdown-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
html2md = "0.2.15"
readability = "0.3.0"
reqwest = { version = "0.13.1", features = ["blocking"] }
url = "2.5.7"
